version: '3.3'
services:
  mysql-datastore:
    container_name: mysql-datastore
    image: mariadb:10.3.24-focal
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=debezium
      - MYSQL_PASSWORD=debezium
    volumes:
      - ./mnt/db_mnt/target/mysql_data:/var/lib/mysql
    ports:
      - "0.0.0.0:3306:3306"
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper
    ports:
      - "0.0.0.0:2181:2181"
      - "0.0.0.0:2888:2888"
      - "0.0.0.0:3888:3888"
    volumes:
      - ./mnt/zookeeper/data:/zookeeper/data
      - ./mnt/zookeeper/txns:/zookeeper/txns
  kafka:
    container_name: kafka
    image: debezium/kafka
    ports:
      - "29092:29092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181/kafka
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=3
    volumes:
      - ./mnt/kafka/data:/kafka/data
  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:
      - "0.0.0.0:9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
  elastic-search-0:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elastic-search-0
    environment:
      - node.name=elastic-search-0
      - cluster.name=cluster-0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./mnt/es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana-0:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana-0
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search-0:9200
    ports:
      - 5601:5601